## Data Cleaning

In [28]:
# imports

import pandas as pd

import numpy as np

In [2]:
# read csv file 

df = pd.read_csv("../Data/raw/googleplaystore.csv")
df.head()

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159,19M,"10,000+",Free,0,Everyone,Art & Design,"January 7, 2018",1.0.0,4.0.3 and up
1,Coloring book moana,ART_AND_DESIGN,3.9,967,14M,"500,000+",Free,0,Everyone,Art & Design;Pretend Play,"January 15, 2018",2.0.0,4.0.3 and up
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510,8.7M,"5,000,000+",Free,0,Everyone,Art & Design,"August 1, 2018",1.2.4,4.0.3 and up
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644,25M,"50,000,000+",Free,0,Teen,Art & Design,"June 8, 2018",Varies with device,4.2 and up
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,967,2.8M,"100,000+",Free,0,Everyone,Art & Design;Creativity,"June 20, 2018",1.1,4.4 and up

In [3]:
# checking whether data loaded correctly

df.shape

(10841, 13)

In [4]:
# all columns list

df.columns

Index(['App', 'Category', 'Rating', 'Reviews', 'Size', 'Installs', 'Type',
       'Price', 'Content Rating', 'Genres', 'Last Updated', 'Current Ver',
       'Android Ver'],
      dtype='object')

In [5]:
# data types

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10841 entries, 0 to 10840
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   App             10841 non-null  object
 1   Category        10841 non-null  object
 2   Rating          9367 non-null   float64
 3   Reviews         10841 non-null  object
 4   Size            10841 non-null  object
 5   Installs        10841 non-null  object
 6   Type            10840 non-null  object
 7   Price           10841 non-null  object
 8   Content Rating  10840 non-null  object
 9   Genres          10841 non-null  object
 10  Last Updated    10841 non-null  object
 11  Current Ver     10833 non-null  object
 12  Android Ver     10838 non-null  object
dtypes: float64(1), object(12)
memory usage: 1.1+ MB

In [6]:
# checking missing value

df.isnull().sum()

App                  0
Category             0
Rating            1474
Reviews              0
Size                 0
Installs             0
Type                 1
Price                0
Content Rating       1
Genres               0
Last Updated         0
Current Ver          8
Android Ver          3
dtype: int64

In [7]:
# check duplicates

df.duplicated().sum()

np.int64(483)

In [8]:
# remove duplicates

df = df.drop_duplicates()
df.shape

(10358, 13)

In [9]:
# checking remaining missing value

df.isnull().sum()

App                  0
Category             0
Rating            1465
Reviews              0
Size                 0
Installs             0
Type                 1
Price                0
Content Rating       1
Genres               0
Last Updated         0
Current Ver          8
Android Ver          3
dtype: int64

### Cleaning Rating Column

In [10]:
# understanding rating using describe

df['Rating'].describe()

count    8893.000000
mean        4.189542
std         0.545452
min         1.000000
25%         4.000000
50%         4.300000
75%         4.500000
max        19.000000
Name: Rating, dtype: float64

In [11]:
# finding invalid rating (usually google rating should be between 1 to 5)

df[df['Rating'] > 5][['App', 'Category', 'Rating']]

                                           App Category  Rating
10472  Life Made WI-Fi Touchscreen Photo Frame      1.9    19.0

In [12]:
# inspecting entire problematic row

df.loc[10472]

App               Life Made WI-Fi Touchscreen Photo Frame
Category                                              1.9
Rating                                               19.0
Reviews                                              3.0M
Size                                               1,000+
Installs                                             Free
Type                                                    0
Price                                            Everyone
Content Rating                                        NaN
Genres                                  February 11, 2018
Last Updated                                       1.0.19
Current Ver                                    4.0 and up
Android Ver                                           NaN
Name: 10472, dtype: object

In [13]:
# currecting problematic row

df.loc[10472] = [ 
    'Life Made WI-Fi Touchscreen Photo Frame',
    'LIFESTYLE',
    1.9,
    19,
    '3.0M',
    '1000+',
    'Free',
    '0',
    'Everyone',
    'Lifestyle',
    'February 11, 2018',
    '1.0.19',
    '4.0 and up'
]

df.loc[10472]

App               Life Made WI-Fi Touchscreen Photo Frame
Category                                        LIFESTYLE
Rating                                                1.9
Reviews                                                19
Size                                                 3.0M
Installs                                            1000+
Type                                                 Free
Price                                                   0
Content Rating                                   Everyone
Genres                                          Lifestyle
Last Updated                            February 11, 2018
Current Ver                                        1.0.19
Android Ver                                    4.0 and up
Name: 10472, dtype: object

In [14]:
#checking again rating 

df[df['Rating'] > 5][['App', 'Rating']]

Empty DataFrame
Columns: [App, Rating]
Index: []

In [15]:
# verifying missing rating

df['Rating'].isnull().sum()

np.int64(1465)

### Cleaning Type Column

In [16]:
# checking missing type value 

df[df['Type'].isnull()][['App', 'Category', 'Rating', 'Reviews', 'Installs', 'Price']]

                            App Category  Rating Reviews Installs Price
9148  Command & Conquer: Rivals   FAMILY     NaN       0        0     0

In [17]:
# Filling missing Type

df.loc[df['Type'].isnull(), 'Type'] = 'Free'

In [18]:
df['Type'].isnull().sum()

np.int64(0)

### Content Rating

In [19]:
# finding missing Content Rating

df[df['Content Rating'].isnull()]

Empty DataFrame
Columns: [App, Category, Rating, Reviews, Size, Installs, Type, Price, Content Rating, Genres, Last Updated, Current Ver, Android Ver]
Index: []

### Cleaning Current Ver

In [20]:
missing_current_ver = df[df['Current Ver'].isnull()]
print('Missing Current Ver:', len(missing_current_ver))
missing_current_ver[['App', 'Category', 'Current Ver', 'Android Ver']]

Missing Current Ver: 8

,App,Category,Current Ver,Android Ver
15,Learn To Draw Kawaii Characters,ART_AND_DESIGN,NaN,4.2 and up
1553,Market Update Helper,LIBRARIES_AND_DEMO,NaN,1.5 and up
6322,Virtual DJ Sound Mixer,TOOLS,NaN,4.0 and up
6803,BT Master,FAMILY,NaN,1.6 and up
7333,Dots puzzle,FAMILY,NaN,4.0 and up
7407,Calculate My IQ,FAMILY,NaN,2.3 and up
7730,UFO-CQ,TOOLS,NaN,2.0 and up
10342,La Fe de Jesus,BOOKS_AND_REFERENCE,NaN,3.0 and up

### Android Ver

In [21]:
# checking missing value in android ver

missing_android_ver = df[df['Android Ver'].isnull()]

print("Missing Android Ver:", len(missing_android_ver))

missing_android_ver[['App', 'Category', 'Current Ver', 'Android Ver']]

Missing Android Ver: 2

                         App         Category Current Ver Android Ver
4453  [substratum] Vacuum: P  PERSONALIZATION         4.4         NaN
4490    Pi Dark [substratum]  PERSONALIZATION         1.1         NaN

In [22]:
df.isnull().sum()

App                  0
Category             0
Rating            1465
Reviews              0
Size                 0
Installs             0
Type                 0
Price                0
Content Rating       0
Genres               0
Last Updated         0
Current Ver          8
Android Ver          2
dtype: int64

In [23]:
df['Android Ver'].head(20)

0     4.0.3 and up
1     4.0.3 and up
2     4.0.3 and up
3       4.2 and up
4       4.4 and up
5       2.3 and up
6     4.0.3 and up
7       4.2 and up
8       3.0 and up
9     4.0.3 and up
10      4.1 and up
11      4.0 and up
12      4.1 and up
13      4.4 and up
14      2.3 and up
15      4.2 and up
16      4.1 and up
17      2.3 and up
18    4.0.3 and up
19      4.1 and up
Name: Android Ver, dtype: object

In [24]:
df['Android Ver'].value_counts()

Android Ver
4.1 and up            2379
4.0.3 and up          1451
4.0 and up            1338
Varies with device    1221
4.4 and up             894
2.3 and up             643
5.0 and up             546
4.2 and up             387
2.3.3 and up           279
2.2 and up             239
3.0 and up             237
4.3 and up             235
2.1 and up             133
1.6 and up             116
6.0 and up              58
7.0 and up              42
3.2 and up              36
2.0 and up              32
5.1 and up              22
1.5 and up              20
4.4W and up             11
3.1 and up              10
2.0.1 and up             7
8.0 and up               6
7.1 and up               3
5.0 - 8.0                2
4.0.3 - 7.1.1            2
1.0 and up               2
7.0 - 7.1.1              1
4.1 - 7.1.1              1
5.0 - 6.0                1
2.2 - 7.1.1              1
5.0 - 7.1.1              1
Name: count, dtype: int64

In [29]:
df.loc[df['Android Ver'] == 'Varies with device', 'Android Ver'] = np.nan
df['Android Ver'].isnull().sum()

np.int64(1223)

In [30]:
df['Android Ver'].dtype

dtype('O')

### Reviews Column

In [31]:
# converting Reviews to numeric

df['Reviews'] = pd.to_numeric(df['Reviews'])
df['Reviews'].dtype

dtype('int64')

In [32]:
# check Reeviews Col

df['Reviews'].head(10)

0       159
1       967
2     87510
3    215644
4       967
5       167
6       178
7     36815
8     13791
9       121
Name: Reviews, dtype: int64

In [33]:
# convert Reviews to Numeric

df['Reviews'] = pd.to_numeric(df['Reviews'])
df['Reviews'].dtype

dtype('int64')

### Size Col

In [34]:
# Clean size column

df['Size'].head(20)

0      19M
1      14M
2     8.7M
3      25M
4     2.8M
5     5.6M
6      19M
7      29M
8      33M
9     3.1M
10     28M
11     12M
12     20M
13     21M
14     37M
15    2.7M
16    5.5M
17     17M
18     39M
19     31M
Name: Size, dtype: object

In [35]:
df['Size'].value_counts().head(20)

Size
Varies with device    1526
11M                    188
13M                    186
12M                    186
14M                    182
15M                    174
17M                    155
26M                    145
16M                    143
19M                    135
10M                    133
20M                    131
25M                    131
21M                    130
24M                    129
18M                    124
23M                    109
22M                    108
29M                     95
27M                     94
Name: count, dtype: int64

In [36]:
# checking size contains KB values

df[df['Size'].str.contains('k', case=False, na=False)]['Size'].head(20)

58      201k
209      23k
384      79k
450     118k
458     695k
479      18k
768     556k
775     526k
1019    334k
1521    232k
1523    624k
1532    8.5k
1542     41k
1544    292k
1553     11k
2244    704k
2263    862k
2267    899k
2273    378k
2278    266k
Name: Size, dtype: object

In [37]:
# convert Size to MB

df['Size_MB'] = df['Size'].apply(
    lambda x: float(x[:-1])/1024 if x[-1].lower()=='k'
    else float(x[:-1]) if x[-1].lower()=='m'
    else None
)

In [38]:
df[['Size', 'Size_MB']].head(20)

    Size  Size_MB
0    19M     19.0
1    14M     14.0
2   8.7M      8.7
3    25M     25.0
4   2.8M      2.8
5   5.6M      5.6
6    19M     19.0
7    29M     29.0
8    33M     33.0
9   3.1M      3.1
10   28M     28.0
11   12M     12.0
12   20M     20.0
13   21M     21.0
14   37M     37.0
15  2.7M      2.7
16  5.5M      5.5
17   17M     17.0
18   39M     39.0
19   31M     31.0

In [39]:
df[df['Size'].str.contains('k', case=False, na=False)][['Size', 'Size_MB']].head(10)

      Size   Size_MB
58    201k  0.196289
209    23k  0.022461
384    79k  0.077148
450   118k  0.115234
458   695k  0.678711
479    18k  0.017578
768   556k  0.542969
775   526k  0.513672
1019  334k  0.326172
1521  232k  0.226562

In [40]:
# replace size('Varies with device') into NaN

import numpy as np

df.loc[df['Size']=='Varies with device', 'Size_MB'] = np.nan

df['Size_MB'].isnull().sum()

np.int64(1526)

In [41]:
# Verify the Size_MB column

df[['Size', 'Size_MB']].tail(10)

                     Size    Size_MB
10831                9.8M   9.800000
10832                582k   0.568359
10833                619k   0.604492
10834                2.6M   2.600000
10835                9.6M   9.600000
10836                 53M  53.000000
10837                3.6M   3.600000
10838                9.5M   9.500000
10839  Varies with device        NaN
10840                 19M  19.000000

### Installs Col

In [42]:
# Inspecting

df['Installs'].head(20)

0         10,000+
1        500,000+
2      5,000,000+
3     50,000,000+
4        100,000+
5         50,000+
6         50,000+
7      1,000,000+
8      1,000,000+
9         10,000+
10     1,000,000+
11     1,000,000+
12    10,000,000+
13       100,000+
14       100,000+
15         5,000+
16       500,000+
17        10,000+
18     5,000,000+
19    10,000,000+
Name: Installs, dtype: object

In [43]:
# check unique values 

df['Installs'].unique()

array(['10,000+', '500,000+', '5,000,000+', '50,000,000+', '100,000+',
       '50,000+', '1,000,000+', '10,000,000+', '5,000+', '100,000,000+',
       '1,000,000,000+', '1,000+', '500,000,000+', '50+', '100+', '500+',
       '10+', '1+', '5+', '0+', '0', '1000+'], dtype=object)

In [44]:
# Fix only the inconsistent 1000+

df['Installs']=df['Installs'].replace('1000+', '1,000+')
df['Installs'].unique()

array(['10,000+', '500,000+', '5,000,000+', '50,000,000+', '100,000+',
       '50,000+', '1,000,000+', '10,000,000+', '5,000+', '100,000,000+',
       '1,000,000,000+', '1,000+', '500,000,000+', '50+', '100+', '500+',
       '10+', '1+', '5+', '0+', '0'], dtype=object)

In [45]:
df['Installs'] = df['Installs'].str.replace(',', '', regex=False)

df['Installs'] = df['Installs'].str.replace('+', '', regex=False)

df['Installs'] = pd.to_numeric(df['Installs'])

In [46]:
df['Installs'].dtype

dtype('int64')

In [47]:
df['Installs'].head(20)

0        10000
1       500000
2      5000000
3     50000000
4       100000
5        50000
6        50000
7      1000000
8      1000000
9        10000
10     1000000
11     1000000
12    10000000
13      100000
14      100000
15        5000
16      500000
17       10000
18     5000000
19    10000000
Name: Installs, dtype: int64

### Type Col

In [48]:
# inspect Type col

df['Type'].value_counts()

Type
Free    9593
Paid     765
Name: count, dtype: int64

In [49]:
df['Type'].dtype

dtype('O')

### Price Col

In [50]:
# inspect price col

df['Price'].head(20)

0     0
1     0
2     0
3     0
4     0
5     0
6     0
7     0
8     0
9     0
10    0
11    0
12    0
13    0
14    0
15    0
16    0
17    0
18    0
19    0
Name: Price, dtype: object

In [51]:
df['Price'].unique()

array(['0', '$4.99', '$3.99', '$6.99', '$1.49', '$2.99', '$7.99', '$5.99',
       '$3.49', '$1.99', '$9.99', '$7.49', '$0.99', '$9.00', '$5.49',
       '$10.00', '$24.99', '$11.99', '$79.99', '$16.99', '$14.99',
       '$1.00', '$29.99', '$12.99', '$2.49', '$10.99', '$1.50', '$19.99',
       '$15.99', '$33.99', '$74.99', '$39.99', '$3.95', '$4.49', '$1.70',
       '$8.99', '$2.00', '$3.88', '$25.99', '$399.99', '$17.99',
       '$400.00', '$3.02', '$1.76', '$4.84', '$4.77', '$1.61', '$2.50',
       '$1.59', '$6.49', '$1.29', '$5.00', '$13.99', '$299.99', '$379.99',
       '$37.99', '$18.99', '$389.99', '$19.90', '$8.49', '$1.75',
       '$14.00', '$4.85', '$46.99', '$109.99', '$154.99', '$3.08',
       '$2.59', '$4.80', '$1.96', '$19.40', '$3.90', '$4.59', '$15.46',
       '$3.04', '$4.29', '$2.60', '$3.28', '$4.60', '$28.99', '$2.95',
       '$2.90', '$1.97', '$200.00', '$89.99', '$2.56', '$30.99', '$3.61',
       '$394.99', '$1.26', '$1.20', '$1.04'], dtype=object)

In [52]:
# remove $ sign

df['Price'] = df['Price'].str.replace('$','',regex=False)
df['Price'].unique()

array(['0', '4.99', '3.99', '6.99', '1.49', '2.99', '7.99', '5.99',
       '3.49', '1.99', '9.99', '7.49', '0.99', '9.00', '5.49', '10.00',
       '24.99', '11.99', '79.99', '16.99', '14.99', '1.00', '29.99',
       '12.99', '2.49', '10.99', '1.50', '19.99', '15.99', '33.99',
       '74.99', '39.99', '3.95', '4.49', '1.70', '8.99', '2.00', '3.88',
       '25.99', '399.99', '17.99', '400.00', '3.02', '1.76', '4.84',
       '4.77', '1.61', '2.50', '1.59', '6.49', '1.29', '5.00', '13.99',
       '299.99', '379.99', '37.99', '18.99', '389.99', '19.90', '8.49',
       '1.75', '14.00', '4.85', '46.99', '109.99', '154.99', '3.08',
       '2.59', '4.80', '1.96', '19.40', '3.90', '4.59', '15.46', '3.04',
       '4.29', '2.60', '3.28', '4.60', '28.99', '2.95', '2.90', '1.97',
       '200.00', '89.99', '2.56', '30.99', '3.61', '394.99', '1.26',
       '1.20', '1.04'], dtype=object)

In [53]:
# converting price to numeric

df['Price'] = pd.to_numeric(df['Price'])
df['Price'].dtype

dtype('float64')

### Last Updated Col

In [54]:
# inspect Last Updated Col

df['Last Updated'].head(20)

0        January 7, 2018
1       January 15, 2018
2         August 1, 2018
3           June 8, 2018
4          June 20, 2018
5         March 26, 2017
6         April 26, 2018
7          June 14, 2018
8     September 20, 2017
9           July 3, 2018
10      October 27, 2017
11         July 31, 2018
12         April 2, 2018
13         June 26, 2018
14        August 3, 2018
15          June 6, 2018
16         July 31, 2018
17      November 7, 2017
18        August 3, 2018
19         July 30, 2018
Name: Last Updated, dtype: object

In [55]:
# Convert Last Updated to datetime

df['Last Updated'] = pd.to_datetime(df['Last Updated'])
df['Last Updated'].dtype

dtype('<M8[ns]')

In [56]:
df[['Last Updated']].head(10)

  Last Updated
0   2018-01-07
1   2018-01-15
2   2018-08-01
3   2018-06-08
4   2018-06-20
5   2017-03-26
6   2018-04-26
7   2018-06-14
8   2017-09-20
9   2018-07-03

### Current Ver Col

In [57]:
df['Current Ver'].head(20)

0                  1.0.0
1                  2.0.0
2                  1.2.4
3     Varies with device
4                    1.1
5                    1.0
6                    1.1
7               6.1.61.1
8                  2.9.2
9                    2.8
10                 1.0.4
11                1.0.15
12                   3.8
13                 1.0.4
14                 1.2.3
15                   NaN
16                   3.1
17                   1.0
18                 2.2.5
19                 5.5.4
Name: Current Ver, dtype: object

In [58]:
df['Current Ver'].value_counts().head(20)

Current Ver
Varies with device    1302
1.0                    802
1.1                    260
1.2                    177
2.0                    149
1.3                    142
1.0.0                  135
1.0.1                  115
1.4                     87
1.5                     81
1.0.2                   80
1.6                     65
1.0.3                   61
3.0                     59
2.1                     59
1.0.4                   57
1.7                     53
2.0.0                   51
1.1.0                   49
1.1.1                   48
Name: count, dtype: int64

In [59]:
# Replace "Varies with device" with missing value

df.loc[df['Current Ver'] == 'Varies with device', 'Current Ver'] = np.nan

In [60]:
df['Current Ver'].isnull().sum()

np.int64(1310)

In [61]:
df['Current Ver'].dtype

dtype('O')

In [62]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 10358 entries, 0 to 10840
Data columns (total 14 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   App             10358 non-null  object
 1   Category        10358 non-null  object
 2   Rating          8893 non-null   float64
 3   Reviews         10358 non-null  int64
 4   Size            10358 non-null  object
 5   Installs        10358 non-null  int64
 6   Type            10358 non-null  object
 7   Price           10358 non-null  float64
 8   Content Rating  10358 non-null  object
 9   Genres          10358 non-null  object
 10  Last Updated    10358 non-null  datetime64[ns]
 11  Current Ver     9048 non-null   object
 12  Android Ver     9135 non-null   object
 13  Size_MB         8832 non-null   float64
dtypes: datetime64[ns](1), float64(3), int64(2), object(8)
memory usage: 1.4+ MB

## EDA

##### 1. Which app Categories have the most apps?

In [63]:

df['Category'].value_counts()

Category
FAMILY                 1943
GAME                   1121
TOOLS                   843
BUSINESS                427
MEDICAL                 408
PRODUCTIVITY            407
PERSONALIZATION         388
LIFESTYLE               374
COMMUNICATION           366
FINANCE                 360
SPORTS                  351
PHOTOGRAPHY             322
HEALTH_AND_FITNESS      306
SOCIAL                  280
NEWS_AND_MAGAZINES      264
TRAVEL_AND_LOCAL        237
BOOKS_AND_REFERENCE     230
SHOPPING                224
DATING                  196
VIDEO_PLAYERS           175
MAPS_AND_NAVIGATION     137
EDUCATION               130
FOOD_AND_DRINK          124
ENTERTAINMENT           111
LIBRARIES_AND_DEMO       85
AUTO_AND_VEHICLES        85
WEATHER                  82
HOUSE_AND_HOME           80
ART_AND_DESIGN           65
EVENTS                   64
COMICS                   60
PARENTING                60
BEAUTY                   53
Name: count, dtype: int64

In [64]:
# total installs by category

df.groupby('Category')['Installs'].sum().sort_values(ascending = False)

Category
GAME                   31544024415
COMMUNICATION          24152276251
SOCIAL                 12513867902
PRODUCTIVITY           12463091369
TOOLS                  11452771915
FAMILY                 10041692505
PHOTOGRAPHY             9721247655
TRAVEL_AND_LOCAL        6361887146
VIDEO_PLAYERS           6222002720
NEWS_AND_MAGAZINES      5393217760
SHOPPING                2573348785
ENTERTAINMENT           2455660000
PERSONALIZATION         2074494782
BOOKS_AND_REFERENCE     1916469576
SPORTS                  1528574498
HEALTH_AND_FITNESS      1361022512
BUSINESS                 863664865
FINANCE                  770348734
MAPS_AND_NAVIGATION      724281890
LIFESTYLE                534824539
EDUCATION                533952000
WEATHER                  426100520
FOOD_AND_DRINK           257898751
DATING                   206536107
HOUSE_AND_HOME           125212461
ART_AND_DESIGN           124338100
LIBRARIES_AND_DEMO        62995910
COMICS                    56086150
AUTO_AND_VEHICLES         53130211
MEDICAL                   42204177
PARENTING                 31521110
BEAUTY                    27197050
EVENTS                    15973161
Name: Installs, dtype: int64

In [65]:
# Average rating by Category

df.groupby('Category')['Rating'].mean().sort_values(ascending=False)

Category
EVENTS                 4.435556
EDUCATION              4.375969
ART_AND_DESIGN         4.358065
BOOKS_AND_REFERENCE    4.347458
PERSONALIZATION        4.333871
PARENTING              4.300000
GAME                   4.281285
BEAUTY                 4.278571
HEALTH_AND_FITNESS     4.261450
SOCIAL                 4.254918
SHOPPING               4.251485
WEATHER                4.244000
SPORTS                 4.225175
PRODUCTIVITY           4.201796
FAMILY                 4.191153
AUTO_AND_VEHICLES      4.190411
PHOTOGRAPHY            4.182895
MEDICAL                4.182450
LIBRARIES_AND_DEMO     4.178462
HOUSE_AND_HOME         4.164706
FOOD_AND_DRINK         4.164151
COMICS                 4.155172
COMMUNICATION          4.151466
ENTERTAINMENT          4.136036
NEWS_AND_MAGAZINES     4.128505
FINANCE                4.127445
BUSINESS               4.102593
TRAVEL_AND_LOCAL       4.094146
LIFESTYLE              4.088889
VIDEO_PLAYERS          4.063750
MAPS_AND_NAVIGATION    4.051613
TOOLS                  4.047411
DATING                 3.971698
Name: Rating, dtype: float64

In [66]:
# Reviews by category

df.groupby('Category')['Reviews'].sum().sort_values(ascending=False)

Category
GAME                   1415536650
COMMUNICATION           601273552
SOCIAL                  533576829
FAMILY                  396771969
TOOLS                   273185044
PHOTOGRAPHY             204297410
VIDEO_PLAYERS           110380188
PRODUCTIVITY            102554498
SHOPPING                 94931162
PERSONALIZATION          75193163
SPORTS                   65322708
TRAVEL_AND_LOCAL         55565160
ENTERTAINMENT            47570716
NEWS_AND_MAGAZINES       38245873
HEALTH_AND_FITNESS       30845186
MAPS_AND_NAVIGATION      30659254
EDUCATION                23165500
BOOKS_AND_REFERENCE      21873227
FINANCE                  16999891
WEATHER                  14604735
LIFESTYLE                12820594
BUSINESS                 12358171
FOOD_AND_DRINK            7671576
DATING                    5545397
COMICS                    3383276
HOUSE_AND_HOME            2794772
ART_AND_DESIGN            1714440
MEDICAL                   1396757
AUTO_AND_VEHICLES         1163666
LIBRARIES_AND_DEMO        1037118
PARENTING                  958331
BEAUTY                     396240
EVENTS                     161018
Name: Reviews, dtype: int64

#### 2. How many apps are Free vs Paid?

In [67]:
df['Type'].value_counts()

Type
Free    9593
Paid     765
Name: count, dtype: int64

In [68]:
# Compare average installs for Free vs Paid

df.groupby('Type')['Installs'].mean()

Type
Free    1.527809e+07
Paid    9.049135e+04
Name: Installs, dtype: float64

In [69]:
# Compare average ratings: Free vs Paid

df.groupby('Type')['Rating'].mean()

Type
Free    4.182150
Paid    4.261501
Name: Rating, dtype: float64

In [70]:
# Compare average reviews: Free vs Paid

df.groupby('Type')['Reviews'].mean()

Type
Free    437282.409048
Paid     11900.550327
Name: Reviews, dtype: float64

#### 3. Relationship between installs and reviews

In [71]:
df[['Installs','Reviews']].corr()

          Installs   Reviews
Installs  1.000000  0.634998
Reviews   0.634998  1.000000

#### 4. Distribution of app ratings

In [72]:
df['Rating'].describe()

count    8893.000000
mean        4.187619
std         0.522910
min         1.000000
25%         4.000000
50%         4.300000
75%         4.500000
max         5.000000
Name: Rating, dtype: float64

#### 5. Top 10 apps by install

In [73]:
df[['App', 'Category', 'Installs']].sort_values('Installs', ascending=False).head(10)

                            App            Category    Installs
3234                     Google               TOOLS  1000000000
2554                    Google+              SOCIAL  1000000000
2545                  Instagram              SOCIAL  1000000000
3736                Google News  NEWS_AND_MAGAZINES  1000000000
5395              Google Photos         PHOTOGRAPHY  1000000000
2544                   Facebook              SOCIAL  1000000000
2884              Google Photos         PHOTOGRAPHY  1000000000
3117  Maps - Navigate & Explore    TRAVEL_AND_LOCAL  1000000000
1654             Subway Surfers                GAME  1000000000
3687    Google Play Movies & TV       VIDEO_PLAYERS  1000000000

In [74]:
## checking apps have duplicates
df['App'].duplicated().sum()

np.int64(698)

In [75]:
df['App'].value_counts().head(10)

App
ROBLOX                            9
8 Ball Pool                       7
Helix Jump                        6
Bubble Shooter                    6
Zombie Catchers                   6
Temple Run 2                      5
Zombie Tsunami                    5
Granny                            5
Angry Birds Classic               5
Duolingo: Learn Languages Free    5
Name: count, dtype: int64

In [76]:
df[df['App'] == 'ROBLOX'][['App', 'Category', 'Rating', 'Reviews', 'Installs', 'Type', 'Last Updated']]

         App Category  Rating  Reviews   Installs  Type Last Updated
1653  ROBLOX     GAME     4.5  4447388  100000000  Free   2018-07-31
1701  ROBLOX     GAME     4.5  4447346  100000000  Free   2018-07-31
1748  ROBLOX     GAME     4.5  4448791  100000000  Free   2018-07-31
1841  ROBLOX     GAME     4.5  4449882  100000000  Free   2018-07-31
1870  ROBLOX     GAME     4.5  4449910  100000000  Free   2018-07-31
2016  ROBLOX   FAMILY     4.5  4449910  100000000  Free   2018-07-31
2088  ROBLOX   FAMILY     4.5  4450855  100000000  Free   2018-07-31
2206  ROBLOX   FAMILY     4.5  4450890  100000000  Free   2018-07-31
4527  ROBLOX   FAMILY     4.5  4443407  100000000  Free   2018-07-31

In [77]:
df['App'].nunique()

9660

In [78]:
df.groupby('App')['Category'].nunique().sort_values(ascending=False).head(10)

App
Bubble Shooter                            2
Farm Heroes Saga                          2
Coloring book moana                       2
Barbie™ Fashion Closet                    2
Flow Free                                 2
CppDroid - C/C++ IDE                      2
Food Network                              2
Fuzzy Numbers: Pre-K Number Foundation    2
Candy Bomb                                2
DC Super Hero Girls™                      2
Name: Category, dtype: int64

In [ ]:
#conclusion duplicates rows are not complete duplicates they have diff categories rating reviews etc

#### 6. Most recently updated apps

In [79]:
df[['App', 'Category', 'Last Updated']].sort_values('Last Updated', ascending=False)

,App,Category,Last Updated
10712,Lalafo Pulsuz Elanlar,SHOPPING,2018-08-08
10408,Shoot Hunter-Gun Killer,GAME,2018-08-08
10760,Fast Tract Diet,HEALTH_AND_FITNESS,2018-08-08
10718,BankNordik,FINANCE,2018-08-08
10209,Video Downloader For FB: Save FB Videos 2018,TOOLS,2018-08-08
...,...,...,...
8084,Freecell CY,GAME,2011-04-16
8418,DEER HUNTER CHALLENGE,GAME,2011-04-11
10282,FD Shift Calendar Widget,TOOLS,2011-03-16
7430,CJ Poker Odds Calculator,GAME,2011-01-30
7479,FML F*ck my life + widget,FAMILY,2010-05-21

In [80]:
df['Last Updated'].min(), df['Last Updated'].max()

(Timestamp('2010-05-21 00:00:00'), Timestamp('2018-08-08 00:00:00'))

In [81]:
# Analyse update by year

df['Last Updated'].dt.year.value_counts().sort_index()

Last Updated
2010       1
2011      15
2012      26
2013     108
2014     204
2015     454
2016     789
2017    1826
2018    6935
Name: count, dtype: int64

#### 7. Installs by app type and category

In [82]:
df.groupby(['Category', 'Type'])['Installs'].mean().sort_values(ascending=False).head(15)

Category             Type
COMMUNICATION        Free    7.124164e+07
SOCIAL               Free    4.517640e+07
VIDEO_PLAYERS        Free    3.638557e+07
PRODUCTIVITY         Free    3.288042e+07
PHOTOGRAPHY          Free    3.218301e+07
GAME                 Free    3.036891e+07
TRAVEL_AND_LOCAL     Free    2.827424e+07
ENTERTAINMENT        Free    2.252716e+07
NEWS_AND_MAGAZINES   Free    2.058478e+07
TOOLS                Free    1.496869e+07
SHOPPING             Free    1.159162e+07
BOOKS_AND_REFERENCE  Free    9.487358e+06
PERSONALIZATION      Free    6.765477e+06
WEATHER              Free    5.747142e+06
FAMILY               Free    5.700736e+06
Name: Installs, dtype: float64

##### 8. Checking Paid apps seperately

In [84]:
df[df['Type'] =='Paid'].groupby('Category')['Installs'].mean().sort_values(ascending=False).head(10)

Category
GAME               254216.445783
FAMILY             166849.272727
EDUCATION          150500.000000
WEATHER            101500.000000
ENTERTAINMENT      100000.000000
PHOTOGRAPHY         98937.000000
LIFESTYLE           62058.421053
PERSONALIZATION     51936.512195
SPORTS              51825.625000
PRODUCTIVITY        50430.535714
Name: Installs, dtype: float64

##### 9. Relationship b/w rating and reviews

In [88]:
df[['Rating', 'Reviews']].corr()

           Rating   Reviews
Rating   1.000000  0.068738
Reviews  0.068738  1.000000

##### 10. Relationship b/w installs and reviews

In [90]:
df[['Installs','Reviews']].corr()

          Installs   Reviews
Installs  1.000000  0.634998
Reviews   0.634998  1.000000

##### 11. Average Number of reviews per app by category

In [92]:
df.groupby('Category')['Reviews'].mean().sort_values(ascending=False)

Category
SOCIAL                 1.905632e+06
COMMUNICATION          1.642824e+06
GAME                   1.262745e+06
PHOTOGRAPHY            6.344640e+05
VIDEO_PLAYERS          6.307439e+05
ENTERTAINMENT          4.285650e+05
SHOPPING               4.237998e+05
TOOLS                  3.240629e+05
PRODUCTIVITY           2.519767e+05
TRAVEL_AND_LOCAL       2.344522e+05
MAPS_AND_NAVIGATION    2.237902e+05
FAMILY                 2.042059e+05
PERSONALIZATION        1.937968e+05
SPORTS                 1.861046e+05
EDUCATION              1.781962e+05
WEATHER                1.781065e+05
NEWS_AND_MAGAZINES     1.448707e+05
HEALTH_AND_FITNESS     1.008013e+05
BOOKS_AND_REFERENCE    9.510099e+04
FOOD_AND_DRINK         6.186755e+04
COMICS                 5.638793e+04
FINANCE                4.722192e+04
HOUSE_AND_HOME         3.493465e+04
LIFESTYLE              3.427966e+04
BUSINESS               2.894185e+04
DATING                 2.829284e+04
ART_AND_DESIGN         2.637600e+04
PARENTING              1.597218e+04
AUTO_AND_VEHICLES      1.369019e+04
LIBRARIES_AND_DEMO     1.220139e+04
BEAUTY                 7.476226e+03
MEDICAL                3.423424e+03
EVENTS                 2.515906e+03
Name: Reviews, dtype: float64

##### 12. Median reviews by category

In [93]:
df.groupby('Category')['Reviews'].median().sort_values(ascending=False)

Category
GAME                   51791.0
ENTERTAINMENT          44550.0
PHOTOGRAPHY            40810.0
SHOPPING               19729.5
EDUCATION              17283.5
COMMUNICATION          13729.5
WEATHER                12468.0
SOCIAL                 11588.5
FOOD_AND_DRINK          6312.5
VIDEO_PLAYERS           5692.0
HEALTH_AND_FITNESS      4372.0
HOUSE_AND_HOME          3960.5
PRODUCTIVITY            2965.0
TRAVEL_AND_LOCAL        2719.0
MAPS_AND_NAVIGATION     2681.0
SPORTS                  2486.0
COMICS                  1576.5
FAMILY                   939.0
DATING                   852.5
NEWS_AND_MAGAZINES       731.5
ART_AND_DESIGN           564.0
PARENTING                528.5
TOOLS                    522.0
FINANCE                  476.0
AUTO_AND_VEHICLES        348.0
PERSONALIZATION          287.0
LIFESTYLE                215.0
BOOKS_AND_REFERENCE      206.0
BEAUTY                   187.0
LIBRARIES_AND_DEMO       131.0
EVENTS                    47.0
MEDICAL                   28.0
BUSINESS                  16.0
Name: Reviews, dtype: float64

##### 13. Checking whether newer apps receive more installs

In [95]:
df.groupby(df['Last Updated'].dt.year)['Installs'].mean()

Last Updated
2010    1.000000e+05
2011    1.160473e+06
2012    5.381619e+05
2013    9.545034e+05
2014    1.322722e+06
2015    9.194724e+05
2016    1.757244e+06
2017    2.112931e+06
2018    2.026898e+07
Name: Installs, dtype: float64

##### 14. Checking weather recently updated apps also have higher ratings

In [96]:
df.groupby(df['Last Updated'].dt.year)['Rating'].mean()

Last Updated
2010    4.200000
2011    3.966667
2012    3.785714
2013    4.069565
2014    4.036757
2015    4.064491
2016    4.039342
2017    4.094033
2018    4.241508
Name: Rating, dtype: float64

##### 15. Paid app percentage by category

In [97]:
df.groupby('Category')['Type'].apply(lambda x: (x=='Paid').mean()*100).sort_values(ascending=False)

Category
PERSONALIZATION        21.134021
MEDICAL                20.588235
BOOKS_AND_REFERENCE    12.173913
WEATHER                 9.756098
FAMILY                  9.624292
TOOLS                   9.252669
GAME                    7.404103
COMMUNICATION           7.377049
PRODUCTIVITY            6.879607
SPORTS                  6.837607
PHOTOGRAPHY             6.211180
LIFESTYLE               5.080214
TRAVEL_AND_LOCAL        5.063291
HEALTH_AND_FITNESS      4.901961
FINANCE                 4.722222
ART_AND_DESIGN          4.615385
MAPS_AND_NAVIGATION     3.649635
DATING                  3.571429
AUTO_AND_VEHICLES       3.529412
PARENTING               3.333333
EDUCATION               3.076923
BUSINESS                2.810304
VIDEO_PLAYERS           2.285714
ENTERTAINMENT           1.801802
FOOD_AND_DRINK          1.612903
EVENTS                  1.562500
LIBRARIES_AND_DEMO      1.176471
SOCIAL                  1.071429
SHOPPING                0.892857
NEWS_AND_MAGAZINES      0.757576
HOUSE_AND_HOME          0.000000
BEAUTY                  0.000000
COMICS                  0.000000
Name: Type, dtype: float64

##### 16. Pricing distribution of paid apps

In [99]:
df[df['Type'] == 'Paid']['Price'].describe()

count    765.000000
mean      13.955556
std       58.406966
min        0.990000
25%        1.490000
50%        2.990000
75%        4.990000
max      400.000000
Name: Price, dtype: float64

#### Price vs Installs
##### 17. Checking whether higher priced apps tend to have fewer installs

In [101]:
df[df['Type']=='Paid'][['Price','Installs']].corr()

            Price  Installs
Price     1.00000  -0.02077
Installs -0.02077   1.00000

##### 18. Compare app count against total installs (competition against demand)

In [105]:
df.groupby('Category').agg(App_Count=('App','count'), Total_Installs=('Installs','sum')).sort_values('Total_Installs',ascending=False)

                     App_Count  Total_Installs
Category
GAME                      1121     31544024415
COMMUNICATION              366     24152276251
SOCIAL                     280     12513867902
PRODUCTIVITY               407     12463091369
TOOLS                      843     11452771915
FAMILY                    1943     10041692505
PHOTOGRAPHY                322      9721247655
TRAVEL_AND_LOCAL           237      6361887146
VIDEO_PLAYERS              175      6222002720
NEWS_AND_MAGAZINES         264      5393217760
SHOPPING                   224      2573348785
ENTERTAINMENT              111      2455660000
PERSONALIZATION            388      2074494782
BOOKS_AND_REFERENCE        230      1916469576
SPORTS                     351      1528574498
HEALTH_AND_FITNESS         306      1361022512
BUSINESS                   427       863664865
FINANCE                    360       770348734
MAPS_AND_NAVIGATION        137       724281890
LIFESTYLE                  374       534824539
EDUCATION                  130       533952000
WEATHER                     82       426100520
FOOD_AND_DRINK             124       257898751
DATING                     196       206536107
HOUSE_AND_HOME              80       125212461
ART_AND_DESIGN              65       124338100
LIBRARIES_AND_DEMO          85        62995910
COMICS                      60        56086150
AUTO_AND_VEHICLES           85        53130211
MEDICAL                    408        42204177
PARENTING                   60        31521110
BEAUTY                      53        27197050
EVENTS                      64        15973161

In [106]:
df.to_csv("../Data/google_play_store_cleaned.csv", index=False)